import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";
import classes from "./layout.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className={classes.navbar}>
          <div>
            <Link href="/shop">Shop</Link>
            <Link href="/cart">Cart</Link>
          </div>
          <Link href="/" className={classes.logo}>
            Turtleneck-Knitter
          </Link>
          <div>
            <Link href="/login">Login</Link>
            <Link href="/mypage">Mypage</Link>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
